"""
mascot_ai/cli/commands/env.py
------------------------------
`mascot-ai env`  — Interactive first-time API key setup for end users.

Keys are stored in ~/.mascot-ai/.env  (never inside site-packages).
"""

import os
import re
import shutil
from pathlib import Path

import click
from rich import print as rprint
from rich.panel import Panel
from rich.prompt import Prompt
from rich.console import Console

console = Console()

# User-level config dir:  ~/.mascot-ai/
USER_CONFIG_DIR = Path.home() / ".mascot-ai"
ENV_FILE        = USER_CONFIG_DIR / ".env"

# Keys to prompt for (in order)
PROMPT_KEYS = [
    {
        "key":         "MISTRAL_API_KEY",
        "label":       "Mistral API Key",
        "url":         "https://console.mistral.ai",
        "required":    True,
        "placeholder": "your_mistral_api_key_here",
    },
    {
        "key":         "OPENROUTER_API_KEY",
        "label":       "OpenRouter API Key (optional fallback)",
        "url":         "https://openrouter.ai/keys",
        "required":    False,
        "placeholder": "your_openrouter_api_key_here",
    },
    {
        "key":         "OPENAI_API_KEY",
        "label":       "OpenAI API Key (optional fallback)",
        "url":         "https://platform.openai.com/api-keys",
        "required":    False,
        "placeholder": "your_openai_api_key_here",
    },
]

ENV_TEMPLATE = """\
# Mascot AI — Environment Configuration
# Generated by: mascot-ai env
# Edit this file to change settings at any time.

# --- Mistral Pixtral Vision (Primary Provider) ---
MISTRAL_API_KEY={MISTRAL_API_KEY}
MISTRAL_MODEL=pixtral-12b-2409

# --- OpenRouter (Optional Fallback) ---
# OPENROUTER_API_KEY={OPENROUTER_API_KEY}
# OPENROUTER_MODEL=openai/gpt-4o-mini

# --- OpenAI (Optional Fallback) ---
# OPENAI_API_KEY={OPENAI_API_KEY}
# OPENAI_MODEL=gpt-4o
"""


def _write_key_to_env(env_path: Path, key: str, value: str):
    """Replace a placeholder value in the .env file."""
    content = env_path.read_text(encoding="utf-8")
    # Uncomment and set the line if it's commented out
    pattern_commented   = re.compile(rf"^#\s*({re.escape(key)}=).*$", re.MULTILINE)
    pattern_uncommented = re.compile(rf"^({re.escape(key)}=).*$",      re.MULTILINE)
    if pattern_uncommented.search(content):
        content = pattern_uncommented.sub(rf"\g<1>{value}", content)
    elif pattern_commented.search(content):
        content = pattern_commented.sub(rf"{key}={value}", content)
    else:
        content += f"\n{key}={value}\n"
    env_path.write_text(content, encoding="utf-8")


@click.command("env")
@click.option("--force", "-f", is_flag=True, default=False,
              help="Re-run setup even if .env already exists.")
def env_cmd(force: bool):
    """Configure your API keys for Mascot AI (run this first!)."""

    rprint(Panel.fit(
        "[bold cyan]🔑  Mascot AI — First-Time Setup[/bold cyan]\n"
        "[dim]This will configure your API keys.[/dim]",
        border_style="cyan",
    ))

    # Create config dir
    USER_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    if ENV_FILE.exists() and not force:
        rprint(f"\n[green]✔[/green]  Config already exists at [dim]{ENV_FILE}[/dim]")
        rprint("[dim]Run [bold]mascot-ai env --force[/bold] to reconfigure.[/dim]\n")
        return

    # Write template
    ENV_FILE.write_text(
        ENV_TEMPLATE.format(
            MISTRAL_API_KEY="your_mistral_api_key_here",
            OPENROUTER_API_KEY="your_openrouter_api_key_here",
            OPENAI_API_KEY="your_openai_api_key_here",
        ),
        encoding="utf-8",
    )
    rprint(f"\n[green]✔[/green]  Config created at [bold]{ENV_FILE}[/bold]\n")

    rprint("[bold white]Please enter your API keys:[/bold white]")
    rprint("[dim]Press Enter to skip optional keys. Edit [bold]~/.mascot-ai/.env[/bold] "
           "anytime to change them.[/dim]\n")

    for item in PROMPT_KEYS:
        tag = "[bold red](required)[/bold red]" if item["required"] else "[dim](optional)[/dim]"
        rprint(f"  [bold yellow]{item['label']}[/bold yellow] {tag}")
        rprint(f"  [dim]Get yours at: {item['url']}[/dim]")

        while True:
            value = Prompt.ask(
                f"  [cyan]{item['key']}[/cyan]",
                default="" if not item["required"] else None,
                password=True,
                console=console,
            )
            if not value and not item["required"]:
                rprint("  [dim]Skipped (optional)[/dim]\n")
                break
            if not value and item["required"]:
                rprint("  [red]This key is required. Please enter a value.[/red]")
                continue
            _write_key_to_env(ENV_FILE, item["key"], value)
            rprint("  [green]Saved.[/green]\n")
            break

    rprint(Panel.fit(
        "[bold green]All set![/bold green]\n\n"
        "Next step: run [bold cyan]mascot-ai start[/bold cyan]\n"
        "[dim]Your keys are in ~/.mascot-ai/.env — keep that file private.[/dim]",
        border_style="green",
    ))
